define build_multiboot =
	@$(SCRIPTS_DIR)/multiboot.py $(1)
endef

BINFO_FLAGS := -a $(CONFIG_UK_ARCH)

ifeq ($(CONFIG_UKPLAT_MEMRNAME),y)
BINFO_FLAGS += -n
endif

define build_bootinfo =
	$(call build_cmd,UKBI,,$(1).bootinfo,\
		$(SCRIPTS_DIR)/mkbootinfo.py $(1) $(1).bootinfo $(BINFO_FLAGS) && \
		$(OBJCOPY) $(1) --update-section .uk_bootinfo=$(1).bootinfo)
endef

define build_static_pgtable =
	$(call build_cmd,TNMKPT,,$(2).o,\
		$(STATIC_PAGE_TOOLS) create $(1) $(2) && \
		$(OBJCOPY) -I binary -O elf64-littleaarch64 \
		--rename-section .data=.tn_static_pt \
		--redefine-sym _binary_$(subst /,_,$(2))_start=arm64_bpt_l3_pt0 \
		--redefine-sym _binary_$(subst /,_,$(2))_size=static_pt_size \
		--redefine-sym _binary_$(subst /,_,$(2))_end=static_pt_end \
		$(2) $(2).o)
endef

define update_static_pgtable =
	$(call build_cmd,TNMKPT,,$(2),\
		$(STATIC_PAGE_TOOLS) update $(1) $(2) $(2).update && \
		$(OBJCOPY) $(1) --update-section .tn_static_pt=$(2).update)
endef

define build_efi =
	@$(SCRIPTS_DIR)/mkefi.py $(1)
endef

define build_linux =
	$(call build_cmd,OBJCOPY,,$(1).bin, $(OBJCOPY) -O binary $(1))
	$(call build_cmd,MKLINUX,,$(1).img, $(SCRIPTS_DIR)/mklinux.py $(1) $(2))
endef
